### ISSUE TITLE
Support approximating different math.h functions

### ISSUE THREAD

**Issue by zhixiangteoh** [neel-one/nocap#1]
- Profile different math functions at LLVM pass (i.e., insert before/after prints to different math.h functions)
- `python3 nocap.py -f exp build`, `python3 nocap.py -f log build`

**Comment by neel-one** [comment]
I think this might work out-of-the-box once we remove the hardcode part of the LLVM pass.

**Comment by zhixiangteoh** [comment]
> I think this might work out-of-the-box once we remove the hardcode part of the LLVM pass.

Yes; have some basic changes but just documenting this here
